### ISSUE TITLE
Year labels off by one when browsing descending chronologically

### ISSUE THREAD

**Issue by cassowarii** [aaronsky500/starmen-badge-guide#11]
When browsing badges by creation date in descending order, the year label for each section appears _after_ the section it is supposed to label. This doesn't seem like the expected behaviour. Here is a screenshot of what I'm talking about:
![problem](https://cloud.githubusercontent.com/assets/2374677/8898604/8e79f606-33db-11e5-9fff-4f7b2b2a8bf3.png)
Note that this problem does not occur when browsing in ascending order. However, there's an unlabeled section (for old badges) at the beginning when browsing in ascending order -- perhaps this issue is related to that?

**Comment by aaronsky** [comment]
This is expected behavior, although the intent could definitely be made more clear. The year label notes a difference in year between the items on either side of the divider. In descending order, the item above will be the newest of that year, while the item below will be of the previous year. In ascending order, this behavior is reversed. For example, in this case Kokana is the newest unfiltered badge of 2014, while Hamtaro is the last unfiltered badge of 2013. 

Could you provide more information re: the unlabeled section at the beginning?

**Comment by cassowarii** [comment]
phew, glad we were able to resolve this issue

**Comment by helloiamarfy** [comment]
what year is it
